# Voice Blending POC Configuration

# Model settings
model:
  path: "kokoro-v0_19.pth"  # Path to the Kokoro model weights
  sample_rate: 24000        # Audio sample rate in Hz
  device: "cpu"            # "cpu", "cuda", or "mps" (for Apple Silicon)

# Voice settings
voices:
  directory: "voices"       # Directory containing voice embedding files
  # Available voices by category
  american_female:
    - "af_nicole"
    - "af_bella"
    - "af_sarah"
    - "af_sky"
  british_female:
    - "bf_emma"
    - "bf_isabella"
  american_male:
    - "am_michael"

# Output settings
output:
  directory: "output"      # Directory for generated audio files
  format: "wav"           # Output audio format

# Blending parameters
blending:
  interpolation_points: [0.3, 0.5, 0.7]  # Points for voice interpolation
  methods:                               # Available blending methods
    - "linear"
    - "slerp"
  combinations:                          # Voice combinations to demonstrate
    # Nicole with American females
    - ["af_nicole", "af_bella"]         # Nicole with Bella
    - ["af_nicole", "af_sarah"]         # Nicole with Sarah
    - ["af_nicole", "af_sky"]           # Nicole with Sky
    # Nicole with British females
    - ["af_nicole", "bf_emma"]          # Nicole with Emma
    - ["af_nicole", "bf_isabella"]      # Nicole with Isabella
    # Nicole cross-gender blend
    - ["af_nicole", "am_michael"]       # Nicole with Michael
    # Special three-way blends
    - ["af_nicole", "af_sky", "bf_emma"]    # American-British female blend
    - ["af_nicole", "af_bella", "af_sarah"] # All-American female blend

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
