name: "layered_reasoning_bot"
version: "0.1.0"
description: "A chatbot with layered reasoning capabilities for enhanced understanding and response generation"

# Paths
data_dir: "data/"
output_dir: "outputs/"
model_dir: "models/"

# Core Bot Model Configuration
models:
  intent_recognition:
    model_name: "gpt-4o-mini" #"deepseek/deepseek-chat"
    temperature: 0.5
    max_tokens: 300
  
  feature_extraction:
    model_name: "gpt-4o-mini" #"deepseek/deepseek-chat"
    temperature: 0.1
    max_tokens: 150
  
  strategy_formation:
    decision_method: "bayesian"  # Options: rule_based, bayesian, reinforcement
    confidence_threshold: 0.7
    strategy_options:
      - factual_explanation
      - clarifying_question
      - example_based
      - reframing
  
  response_generation:
    model_name: "gpt-4o-mini" #"deepseek/deepseek-chat"
    temperature: 0.8
    max_tokens: 500
    tone_matching: true

# AI Role Configurations
ai_roles:
  initiator:
    description: "Primary conversation driver, focuses on emotional probing and engagement"
    model:
      model_name: "gpt-4o-mini"  # More capable model for complex interactions
      temperature: 0.7
      max_tokens: 500
      tone_matching: true
    capabilities:
      - emotional_probing
      - cognitive_challenge
      - stress_induction
      - recovery_guidance
  
  observer:
    description: "Analyzes interactions and emotional patterns"
    model:
      model_name: "gpt-4o-mini"  # High reasoning capability for analysis
      temperature: 0.2  # Lower temperature for more analytical responses
      max_tokens: 1000  # Longer responses for detailed analysis
      tone_matching: false
    capabilities:
      - pattern_recognition
      - emotional_analysis
      - behavioral_prediction
      - insight_generation

# Memory Configuration
memory:
  conversation_history_length: 10
  episodic_memory_enabled: true
  memory_persistence: true

# Logging Configuration
logging:
  level: "INFO"
  file: "bot.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Features
features:
  xai_enabled: true
  feedback_collection: true
  goal_tracking: true 